language: java

sudo: false

dist: trusty

jdk:
  - openjdk8
  
before_install:
  - chmod +x mvnw  
  
script: mvn clean install
  
branches:
  only:
  - master
  
cache:
  directories:
  - .autoconf
  - $HOME/.m2
