# the version of docker-compose document
version: "2"

services:
    rexumee:
        build: .
        image: rexumee
        ports:
            - "80:8080"
        volumes:
            - ./pom.xml:/pom.xml
            - ./src:/src